name: battle_live
description: Una aplicación para administrar lives y contadores de donaciones.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  
  # Networking
  socket_io_client: ^2.0.3+1
  
  # State Management
  provider: ^6.0.5
  
  # UI
  cupertino_icons: ^1.0.5
  
  # Utilidades
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Assets para la aplicación
  assets:
    - assets/
